### ISSUE TITLE
simple music widget tries to preload all mp3s

### ISSUE THREAD

**Issue by dreadkopp** [dolatabadi/WordPress-Plugins#8]
hey.

i really like the widget for it's simplicity!

Since i use it in multiple instances i'd suggest a small change in line 68 of simple_music_widget.php.

preload='' -> preload="metadata"

with the original settings the page will be bloated with preloaded mp3s making it extremely big (~20MB). Changing this line brought it down back to sub 1MB.

Thanks for the great widget. It is exactly what i was looking for!

**Comment by dolatabadi** [comment]
@dreadkopp 
Thank you, I have included this change for v 1.2 which was released today.
